#!/usr/bin/env bash
# Build the agentic-graph-analytics BYOC bundle for the Arango Container Manager.
#
# Output: a FLAT tar.gz (entrypoint at the archive root):
#   entrypoint            scripts/platform/entrypoint (line-1 token rule)
#   requirements.txt      runtime deps, installed by the entrypoint on boot
#   graph_analytics_ai/   the package (no __pycache__, no tests)
#   static/               the exported frontend, built for the mount path
#   .env                  BAKED credentials — see the warning below
#
# The platform injects nothing but PORT, so whatever is in .env here is the
# only configuration the deployed service will ever have. That makes the
# tarball itself a secret: `tar -xzf` is one command from plaintext. It is
# gitignored; do not attach it to anything.
#
# The mount prefix is a BUILD input, not a runtime one (NFR-21): the browser
# sees the prefix, the pod does not, so the frontend has to be compiled for the
# path it will be served at. Rebuild if you change --instance or --db.
#
# Usage:
#   scripts/platform/package.sh [OUT] [--instance NAME] [--db NAME] [--global]
#                               [--skip-frontend]
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
OUT="${REPO_ROOT}/aga-service.tar.gz"
INSTANCE="${INSTANCE:-aga}"
DB="${DB:-}"
GLOBAL=1          # the live deployment is global-scoped; --db switches it
SKIP_FRONTEND=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --instance) INSTANCE="$2"; shift 2 ;;
    --db)       DB="$2"; GLOBAL=0; shift 2 ;;
    --global)   GLOBAL=1; DB=""; shift ;;
    --skip-frontend) SKIP_FRONTEND=1; shift ;;
    -*) echo "unknown flag: $1" >&2; exit 2 ;;
    *)  OUT="$1"; shift ;;
  esac
done

# --- resolve connection settings: environment first, then repo-root .env ------
envval() {
  local key="$1"
  if [[ -n "${!key:-}" ]]; then printf '%s' "${!key}"; return; fi
  [[ -f "${REPO_ROOT}/.env" ]] || return 0
  sed -n "s/^[[:space:]]*${key}[[:space:]]*=[[:space:]]*//p" "${REPO_ROOT}/.env" \
    | head -1 | sed 's/^"//; s/"$//; s/^'"'"'//; s/'"'"'$//'
}

ENDPOINT="$(envval ARANGO_ENDPOINT)"
USER_="$(envval ARANGO_USER)"
PASSWORD="$(envval ARANGO_PASSWORD)"
# The product API keeps its metadata in its OWN database, separate from the
# analytics graph. Getting this wrong yields a service that connects happily
# and reports no workspaces.
WORKSPACE_DB="${AGA_WORKSPACE_DB:-aga_workspace}"

[[ -n "${ENDPOINT}" && -n "${USER_}" && -n "${PASSWORD}" ]] || {
  echo "error: need ARANGO_ENDPOINT, ARANGO_USER and ARANGO_PASSWORD (env or .env)" >&2
  exit 1; }
case "${ENDPOINT}" in
  *localhost*|*127.0.0.1*)
    echo "error: ARANGO_ENDPOINT=${ENDPOINT} is loopback — unreachable from the platform" >&2
    exit 1 ;;
esac

if [[ "${GLOBAL}" -eq 1 ]]; then
  PREFIX="/_service/uds/_global/${INSTANCE}"
else
  PREFIX="/_service/uds/_db/${DB}/${INSTANCE}"
fi

echo "==> instance : ${INSTANCE}"
echo "==> scope    : $([[ ${GLOBAL} -eq 1 ]] && echo global || echo "db=${DB}")"
echo "==> prefix   : ${PREFIX}/"
echo "==> metadata : ${WORKSPACE_DB} on ${ENDPOINT}"

# --- frontend: compiled FOR the mount path ------------------------------------
if [[ "${SKIP_FRONTEND}" -eq 0 ]]; then
  echo "==> building the frontend for ${PREFIX}"
  ( cd "${REPO_ROOT}/frontend" \
    && SERVICE_URL_PATH_PREFIX="${PREFIX}" \
       NEXT_PUBLIC_PRODUCT_API_BASE_URL="${PREFIX}" \
       npx next build >/dev/null )
else
  echo "==> --skip-frontend: reusing frontend/out as-is"
fi
[[ -f "${REPO_ROOT}/frontend/out/index.html" ]] || {
  echo "error: frontend/out/index.html missing — the export did not run" >&2; exit 1; }
# Guard the failure mode that is invisible server-side: a root-absolute asset
# resolves against the cluster root and renders a blank page under 200s.
if grep -qE '(src|href)="/(_next|icon|arango)' "${REPO_ROOT}/frontend/out/workspace/index.html"; then
  echo "error: exported assets are root-absolute — they will 404 under ${PREFIX}" >&2
  exit 1
fi

# --- stage --------------------------------------------------------------------
STAGE="$(mktemp -d)"; trap 'rm -rf "${STAGE}"' EXIT
install -m 0644 "${REPO_ROOT}/scripts/platform/entrypoint" "${STAGE}/entrypoint"

cat > "${STAGE}/requirements.txt" <<'REQS'
python-arango>=7.0.0
requests>=2.28.0
python-dotenv>=0.19.0
click>=8.0.0
PyYAML>=6.0
fastapi>=0.110.0
uvicorn[standard]>=0.27.0
REQS

rsync -a --exclude '__pycache__' --exclude '*.pyc' \
      "${REPO_ROOT}/graph_analytics_ai" "${STAGE}/"
cp -R "${REPO_ROOT}/frontend/out" "${STAGE}/static"

# --- the baked .env -----------------------------------------------------------
# Written from an allowlist rather than copied, so a developer's unrelated
# secrets never travel. LLM keys ARE included: the agentic features need them
# and the platform has no way to supply them to a BYOC service.
{
  echo "# Generated by scripts/platform/package.sh — do not edit by hand."
  echo "# This file is why the tarball is a secret."
  echo "ARANGO_ENDPOINT=${ENDPOINT}"
  echo "ARANGO_USER=${USER_}"
  echo "ARANGO_PASSWORD=${PASSWORD}"
  echo "ARANGO_DATABASE=${WORKSPACE_DB}"
  echo "SERVICE_URL_PATH_PREFIX=${PREFIX}"
  echo "AGA_PRODUCT_CORS_ORIGINS=*"
} > "${STAGE}/.env"

LLM_KEYS_BAKED=0
for key in OPENROUTER_API_KEY OPENAI_API_KEY ANTHROPIC_API_KEY LLM_PROVIDER \
           OPENROUTER_MODEL OPENAI_MODEL ANTHROPIC_MODEL; do
  value="$(envval "${key}")"
  if [[ -n "${value}" ]]; then
    echo "${key}=${value}" >> "${STAGE}/.env"
    [[ "${key}" == *_API_KEY ]] && LLM_KEYS_BAKED=1
  fi
done

# --- pack ---------------------------------------------------------------------
tar -czf "${OUT}" -C "${STAGE}" .
SIZE="$(du -h "${OUT}" | cut -f1)"
echo "==> wrote ${OUT} (${SIZE})"
if [[ "${LLM_KEYS_BAKED}" -eq 1 ]]; then
  echo "!!  LLM API keys are baked into this tarball. Treat it as a credential:"
  echo "!!  do not commit it, attach it, or copy it off this machine."
fi
